---
- name: Converge
  hosts: all
  vars:
    foreman_scap_client_manage_repo: true
    foreman_scap_client_server: https://foreman.example.com
    foreman_scap_client_port: 9090
    foreman_scap_client_cron_splay_seed: 42
    foreman_scap_client_http_proxy_server: 'https://proxy.example.com'
    foreman_scap_client_http_proxy_port: 7475
    foreman_scap_client_fetch_remote_resources: true
    foreman_scap_client_timeout: 61
    foreman_scap_client_policies: [
      {
        "id": "1",
        "hour": "12",
        "minute": "1",
        "month": "*",
        "monthday": "*",
        "weekday": "1",
        "profile_id": "",
        "content_path": "/usr/share/xml/scap/ssg/fedora/ssg-fedora-ds.xml",
        "download_path": "/compliance/policies/1/content",
        "tailoring_path": "/var/lib/openscap/ssg-fedora-ds-tailored.xml",
        "tailoring_download_path": "/compliance/policies/1/tailoring"
      }
    ]
  tasks:
    - name: "Test the role with no policies and server"
      ansible.builtin.import_role:
        name: theforeman.foreman_scap_client
      vars:
        foreman_scap_client_server: ''
        foreman_scap_client_policies: []
      tags: molecule-idempotence-notest

    - name: "Test that the role fails when the server variable is empty and a policy is assigned"
      tags: molecule-idempotence-notest
      block:
        - name: "Run the role with an empty server variable (expected to fail)"
          ansible.builtin.include_role:
            name: theforeman.foreman_scap_client
          vars:
            foreman_scap_client_server: ''
          register: role_result
          ignore_errors: true

        - name: "FAIL: The role unexpectedly succeeded"
          ansible.builtin.fail:
            msg: "The role with en empty server variable should have failed, but it succeeded."
          when: not role_result.failed

      rescue:
        - name: "Assert that the role failed."
          ansible.builtin.debug:
            msg: "SUCCESS: The role with an empty server variable failed correctly."

    - name: "Test the role with all variables"
      ansible.builtin.import_role:
        name: theforeman.foreman_scap_client
