---
- name: Prepare
  hosts: all
  tasks:
    - name: 'Install cronie'
      ansible.builtin.dnf:
        name: cronie
        state: present
    - name: 'Install subscription-manager'
      ansible.builtin.dnf:
        name: subscription-manager
        state: present

    - name: Clean dnf package cache
      ansible.builtin.command:
        cmd: dnf clean all
      changed_when: true
