---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: ubuntu24
    image: docker.io/geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2404}-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
scenario:
  name: ubuntu
verifier:
  name: testinfra
lint: flake8
