---
- name: Prepare
  hosts: all
  tasks:
    - name: 'Install dependencies'
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      with_items:
        - systemd-cron
        - python3-debian
        - gnupg

    - name: Configure gpg_key
      ansible.builtin.get_url:
        url: "https://oss.atix.de/atix_gpg.pub"
        dest: "/etc/apt/trusted.gpg.d/foreman_client.asc"
        mode: '0644'

    - name: Configure repository
      ansible.builtin.deb822_repository:
        name: "foreman_client"
        types: "deb"
        uris: "https://oss.atix.de/Ubuntu24LTS/"
        suites: "stable"
        components: "main"
        state: "present"
        signed_by: "/etc/apt/trusted.gpg.d/foreman_client.asc"

    - name: Run apt-get update
      ansible.builtin.apt:
        update_cache: true

    - name: 'Install subscription-manager'
      ansible.builtin.package:
        name: subscription-manager
        state: present

    - name: Cleanup repo
      ansible.builtin.deb822_repository:
        name: "foreman_client"
        state: "absent"

    - name: Cleanup gpg key
      ansible.builtin.file:
        path: "/etc/apt/trusted.gpg.d/foreman_client.asc"
        state: "absent"

    - name: Update cache
      ansible.builtin.apt:
        update_cache: true
